### ISSUE TITLE
您好，请问论文中提到的另外两个数据集是开源的嘛？

### ISSUE THREAD

**Issue by wongsihan** [a1018680161/Few-shot-Transfer-Learning#1]
非常感谢您开源论文的代码，我看到除了PU数据集之外还有SQI数据集和Qianpeng数据集用于测试，但是后两者没有在网上搜索到，请问是开源的嘛？如果是能否提供一下下载链接？如果不是，不知能否通过其他途径获取呢？谢谢。

**Comment by a1018680161** [comment]
感谢关注，SQI数据集和Qianpeng数据集是课题组内部的数据，暂时没有开源，所以只开放了PU数据集相关的部分。后续可能会发布开源数据集供领域内学者研究使用，最新的成果以及资源将会第一时间通过我的github账号以及google scholar账号：https://scholar.google.com.hk/citations?user=FS7clzcAAAAJ&hl=zh-CN发布， 欢迎继续关注。

**Comment by wongsihan** [comment]
感谢回复。我对基于深度学习的轴承故障诊断很感兴趣，看了您的文章很有收获，期待后续的学习资料分享，祝您科研顺利。
