### ISSUE TITLE
关于论文将训练和测试数据随机化的问题

### ISSUE THREAD

**Issue by wongsihan** [a1018680161/Few-shot-Transfer-Learning#3]
你好，我在阅读代码的时候发现，例如finetuneTask类、pu_train类等会将训练或测试的数据随机化（对应代码np.random.shuffle(file)），然后进行fft和1024截取的处理，我想请问一下为什么要对这些原始信号做随机化呢，似乎文章中并未提到这一步的意义是什么，而且似乎对整体模型的准确度似乎没有太多影响？

**Comment by a1018680161** [comment]
选择不同样本进行训练和测试，产生的结果具有随机性，尤其是在少样本情况下，样本的影响尤为显著；通过随机化，然后计算平均精度，可以使结果更可靠

**Comment by wongsihan** [comment]
哦哦，感谢回复，我看错了。。我以为shuffle是改变列的。。。
